### ISSUE TITLE
v3.0.0

### ISSUE THREAD

**Issue by rubiii** [savonrb/savon#473]
This ticket continues the [Wasabi v4.0](https://github.com/savonrb/wasabi/issues/27) milestone ticket which was driving the development for Savon version 3 up until now.

Here is my TODO list for version 3:
- [x] Solve performance problems [#7](https://github.com/savonrb/wasabi/issues/7).
- [x] Support WSDL imports [#1](https://github.com/savonrb/wasabi/issues/1).
- [x] Properly separate operations by service and port.
- [x] Support XML Schema imports.
- [x] Remove the dependency on HTTPI as an HTTP client.
- [x] Parse operation input parameters and generate a map of types for the message body.
- [x] Integrate Wasabi 4.0 with Savon so people can easily test it as soon as possible.
- [x] Add support for message headers defined in the WSDL.
- [x] Finish initial documentation.
- [x] Push to GitHub!
- [x] Add support for attributes.
- [ ] Change the response Hash format to match the request Hash format.
- [ ] Convert Hash values to SOAP values (DateTime, etc) according to the type definition.
- [ ] Support WS-Policy/WS-Addressable (see savonrb/savon#409).
- [ ] Store the proper order of parameters so we can get rid of the `:order!` hack.
- [ ] Support for multipart responses using the new Savon::Multipart gem.
- [ ] Maybe support relative WSDL/Schema import locations? Can't find the specification for this.
- [ ] Switch from symbols to strings (for [#485](https://github.com/savonrb/savon/issues/485))
- [x] Implement Response.header (for [#544](https://github.com/savonrb/savon/issues/544))

Please follow this issue for updates on version 3.
