### ISSUE TITLE
v2.3.0

### ISSUE THREAD

**Issue by rubiii** [savonrb/savon#481]
A list of features, bug fixes and improvements for the upcoming Savon v2.3.0 release.

**Savon**
- [x] [#405](https://github.com/savonrb/savon/pull/405) Improved NTLM support.
- [x] [#424](https://github.com/savonrb/savon/issues/424) Added support for multipart MIME.
- [x] [#470](https://github.com/savonrb/savon/issues/470) Added a local `:soap_header` option to allow setting the SOAP header per request.
- [x] [#402](https://github.com/savonrb/savon/issues/402) Changed the Savon test helper to allow expecting a request without having to specify the message.
- [x] [#450](https://github.com/savonrb/savon/pull/450) Added `response#soap_fault`
  and `response#http_error` which were present in version 1.
- [x] [#474](https://github.com/savonrb/savon/issues/474) Changed `response#header` and
  `response#body` to respect the global `:convert_response_tags_to` and `:strip_namespaces`
  options and return the expected result instead of raising an error.
- [x] [#461](https://github.com/savonrb/savon/issues/461) Fixed two problems related to namespace qualified messages and the element `:order!`.
- [x] [#476](https://github.com/savonrb/savon/issues/476) Fixes a problem where Savon didn't find the correct namespace for the operation (message) tag.
- [x] [#468](https://github.com/savonrb/savon/issues/468) Changed the dependency on Nokogiri to < 1.6, because Nokogiri 1.6 dropped support for Ruby 1.8  
  while Savon version 2 currently still supports this version.

**HTTPI (v2.1.0)**
- [x] [#75](https://github.com/savonrb/httpi/pull/75) New [Rack](https://github.com/rack/rack) adapter.
- [x] [#91](https://github.com/savonrb/httpi/pull/91) New [excon](https://github.com/geemus/excon) adapter.
- [x] [#92](https://github.com/savonrb/httpi/pull/92) New [net-http-persistent](https://github.com/drbrain/net-http-persistent) adapter.
- [x] [#87](https://github.com/savonrb/httpi/pull/87) NTLM support with full domain and server authentication.
- [x] [#71](https://github.com/savonrb/httpi/pull/71) Support for chunked responses.
- [x] [#81](https://github.com/savonrb/httpi/issues/81) Fixes a (probably major) problem with all adapters where SSL certificate options where only passed to the underlying HTTP client when SSL verify mode was set to `:none`.
- [x] [#88](https://github.com/savonrb/httpi/issues/88) Fixes a problem where the timeout and proxy options were not correctly passed to the EM-HTTP-Request client.
- [x] [#69](https://github.com/savonrb/httpi/issues/69) Fixes a problem where the response headers were truncated.
- [x] [#90](https://github.com/savonrb/httpi/issues/90) We now raise an error if you try to use Net/HTTP with HTTP digest authentication, because it is not supported.

**Wasabi (v3.2.0)**
- [x] [#7](https://github.com/savonrb/wasabi/issues/7) Major speed improvements.
- [x] [#25](https://github.com/savonrb/wasabi/issues/25) Fixes a problem where Wasabi escaped an already escaped endpoint URL.
- [x] [#20](https://github.com/savonrb/wasabi/pull/20) Limited support for listing an operation's parameters.  
  Please note that if your WSDL defines imports, this method might not return all types.
- [x] [#15](https://github.com/savonrb/wasabi/pull/15) Fixes a bug where the operation tag name was not correctly extracted from the WSDL document.
- [x] [#16](https://github.com/savonrb/wasabi/pull/16) Various improvements regarding element order and type information.

**Gyoku (v1.1.0)**
- [x] [#30](https://github.com/savonrb/gyoku/pull/30) Support for Arrays of @attributes. Also fixes a couple of related issues.
- [x] [#21](https://github.com/savonrb/gyoku/pull/21) Stop modifying the original Hash. Original issue: #410.

**Nori (v2.3.0)**
- [x] Changed `Nori#find` to ignore namespace prefixes in Hash keys it is searching through. Original issue: #474.
- [x] Limited Nokogiri to < 1.6, because v1.6 dropped support for Ruby 1.8.

To be continued. Follow this ticket for updates.
